Require lens-5.1
Otherwise with `lens < 5.1` you get
```
src/Diagrams/Util.hs:160:34: error:
    Variable not in scope:
      prefixed
        :: [Char]
           -> (FilePath -> Const (First FilePath) FilePath)
           -> p0 String (Const (First FilePath) String)
    |
160 |   hoistMaybe $ config ^? lined . prefixed "package-db: "
    |
```